package com.practicedyad.app.ui.theme

import androidx.compose.runtime.compositionLocalOf
import com.practicedyad.app.data.model.AppLanguage

data class AppStrings(
    // Navigation / Drawer
    val navProfile: String,
    val navTrainingPlans: String,
    val navMyExercises: String,
    val navAthletes: String,
    val navProgress: String,
    val navChat: String,
    val navTrainingConcept: String,
    val navOrganization: String,
    val navSettings: String,
    val navLogout: String,
    // Common actions
    val done: String,
    val add: String,
    val cancel: String,
    val delete: String,
    val save: String,
    val edit: String,
    val search: String,
    val close: String,
    val apply: String,
    val confirm: String,
    val back: String,
    val create: String,
    val start: String,
    val next: String,
    val finish: String,
    // Exercise screen
    val myExercises: String,
    val standardDatabase: String,
    val searchExercise: String,
    val noCustomExercises: String,
    val loadingExercises: String,
    val editImages: String,
    val newExercise: String,
    val chooseExercise: String,
    val createNewExercise: String,
    val fromDatabase: String,
    // Training plan
    val trainingPlans: String,
    val newTrainingPlan: String,
    val editPlan: String,
    val deletePlan: String,
    val addExercise: String,
    val addFocus: String,
    val alternativeExercises: String,
    val addAlternative: String,
    val rounds: String,
    val sets: String,
    val reps: String,
    val pause: String,
    val seconds: String,
    // Settings
    val settings: String,
    val appearance: String,
    val darkMode: String,
    val language: String,
    val weightUnit: String,
    val notifications: String,
    val privacy: String,
    val subscription: String,
    val myRole: String,
    val roleCoach: String,
    val roleAthlete: String,
    val roleBoth: String,
    val shareProgressWithCoach: String,
    val signOut: String,
    // Training plans screen
    val weekdayNames: List<String>,
    val everyXDays: String,
    val freelyChoosable: String,
    val exerciseCount: String,
    val sharePlan: String,
    val sharePlanTitle: String,
    val individualAthletes: String,
    val workoutNotScheduled: String,
    val workoutNotScheduledBody: String,
    val endPlan: String,
    val endPlanTitle: String,
    val endPlanBody: String,
    val newTrainingPlanCreate: String,
    val noPlansCoach: String,
    val noPlansAthlete: String,
    val deletePlanBody: String,
    val exercises: String,
    val noExercisesFound: String,
    val selectAll: String,
    val groupIntoCircuit: String,
    val addExercisesFirst: String,
    val circuitExercisesTitle: String,
    val circuitExercisesBody: String,
    // Workout execution
    val roundOf: String,
    val exerciseOf: String,
    val alternative: String,
    val chooseExerciseTitle: String,
    val setsLabel: String,
    val repsLabel: String,
    val workoutCompleted: String,
    val shareWorkoutQuestion: String,
    val shareWorkout: String,
    val dontShare: String,
    // Home screen
    val todayNoWorkout: String,
    val todayWorkoutTitle: String,
    val completedToday: String,
    val notScheduledTitle: String,
    val notScheduledBody: String,
    val startAnyway: String,
    val navTrainingNotes: String,
    val noNotesYet: String,
    val newNote: String,
    val writeNote: String,
    // Categories (exercise filter)
    val catAll: String,
    val catBack: String,
    val catChest: String,
    val catShoulders: String,
    val catCore: String,
    val catThighs: String,
    val catCalves: String,
    val catGlutes: String,
    val catUpperArms: String,
    val catCoordination: String,
    val catReflection: String,
    val matBodyweight: String,
    val matDumbbells: String,
    val matMachine: String,
    val matOther: String,
    val matAll: String,
)

val GermanStrings = AppStrings(
    navProfile = "Profil",
    navTrainingPlans = "Trainingspläne",
    navMyExercises = "Meine Übungen",
    navAthletes = "Athlet*innen",

    navProgress = "Trainingsfortschritt",
    navChat = "Chat",
    navTrainingConcept = "Trainingskonzept",
    navOrganization = "Organisation",
    navSettings = "Einstellungen",
    navLogout = "Ausloggen",
    done = "Fertig",
    add = "Hinzufügen",
    cancel = "Abbrechen",
    delete = "Löschen",
    save = "Speichern",
    edit = "Bearbeiten",
    search = "Suchen",
    close = "Schließen",
    apply = "Übernehmen",
    confirm = "Bestätigen",
    back = "Zurück",
    create = "Erstellen",
    start = "Starten",
    next = "Weiter",
    finish = "Abschließen",
    myExercises = "Meine Übungen",
    standardDatabase = "Standarddatenbank",
    searchExercise = "Übung suchen…",
    noCustomExercises = "Noch keine eigenen Übungen.\nFüge deine erste Übung hinzu.",
    loadingExercises = "Standardübungen werden geladen…",
    editImages = "Bilder bearbeiten",
    newExercise = "Neue Übung",
    chooseExercise = "Übung wählen",
    createNewExercise = "Neue Übung erstellen",
    fromDatabase = "Datenbank",
    trainingPlans = "Trainingspläne",
    newTrainingPlan = "Neuer Trainingsplan",
    editPlan = "Plan bearbeiten",
    deletePlan = "Trainingsplan löschen",
    addExercise = "Übung hinzufügen",
    addFocus = "Schwerpunkt hinzufügen",
    alternativeExercises = "Alternativübungen",
    addAlternative = "Hinzufügen",
    rounds = "Runden",
    sets = "Sätze",
    reps = "Wdh.",
    pause = "Pause",
    seconds = "Sekunden",
    settings = "Einstellungen",
    appearance = "Erscheinungsbild",
    darkMode = "Dunkles Design",
    language = "Sprache",
    weightUnit = "Gewichtseinheit",
    notifications = "Benachrichtigungen",
    privacy = "Datenschutz",
    subscription = "Abonnement",
    myRole = "Meine Rolle",
    roleCoach = "Trainer",
    roleAthlete = "Athlet*in",
    roleBoth = "Beides",
    shareProgressWithCoach = "Fortschritt mit Coach teilen",
    signOut = "Ausloggen",
    todayNoWorkout = "Heute kein Training geplant.\nGenieße deinen Ruhetag!",
    todayWorkoutTitle = "Heutiges Training",
    completedToday = "Heute abgeschlossen",
    notScheduledTitle = "Nicht für heute geplant",
    notScheduledBody = "Mindestabstand zum letzten Workout nicht erreicht. Das nächste Workout wird erst nach Ablauf des Mindestabstands freigeschaltet.",
    startAnyway = "Trotzdem starten",
    weekdayNames = listOf("Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"),
    everyXDays = "Alle %d Tage",
    freelyChoosable = "Frei wählbar",
    exerciseCount = "%d Übungen",
    roundOf = "Runde %d / %d",
    exerciseOf = "Übung %d / %d",
    alternative = "Alternative",
    chooseExerciseTitle = "Übung wählen",
    setsLabel = "Sätze",
    repsLabel = "Wdh.",
    workoutCompleted = "Workout abgeschlossen!",
    shareWorkoutQuestion = "Möchtest du dein Workout mit deinem Coach teilen?",
    shareWorkout = "Workout teilen",
    dontShare = "Nicht teilen",
    sharePlan = "Teilen",
    sharePlanTitle = "Trainingsplan teilen",
    individualAthletes = "Einzelne Athlet*innen",
    workoutNotScheduled = "Workout nicht für heute geplant",
    workoutNotScheduledBody = "Mindestabstand zum letzten Workout nicht eingehalten. Das Workout wird erst nach Ablauf des Mindestabstands freigeschaltet.",
    endPlan = "Beenden",
    endPlanTitle = "Trainingsplan beenden",
    endPlanBody = "Der Plan wird für alle Athlet*innen beendet und aus ihrer App entfernt.",
    newTrainingPlanCreate = "Neuen Trainingsplan erstellen",
    noPlansCoach = "Noch keine Trainingspläne.\nErstelle deinen ersten Plan.",
    noPlansAthlete = "Kein Trainingsplan geteilt.\nGib deinen Coach-Code ein.",
    deletePlanBody = "Der Trainingsplan wird dauerhaft gelöscht.",
    exercises = "Übungen",
    noExercisesFound = "Keine Übungen gefunden.",
    selectAll = "Alle auswählen",
    groupIntoCircuit = "Übungen zu Circuit gruppieren",
    addExercisesFirst = "Füge zuerst Übungen hinzu.",
    circuitExercisesTitle = "Circuit-Übungen wählen",
    circuitExercisesBody = "Welche Übungen sollen im Circuit absolviert werden?",
    navTrainingNotes = "Trainingsnotizen",
    noNotesYet = "Noch keine Notizen.\nTippe auf + um deine erste Notiz hinzuzufügen.",
    newNote = "Neue Notiz",
    writeNote = "Notiz eingeben…",
    catAll = "Alle",
    catBack = "Rücken",
    catChest = "Brust",
    catShoulders = "Schultern",
    catCore = "Bauch",
    catThighs = "Oberschenkel",
    catCalves = "Unterschenkel",
    catGlutes = "Becken",
    catUpperArms = "Oberarme",
    catCoordination = "Koordination",
    catReflection = "Reflektion",
    matBodyweight = "Ohne Hilfsmittel",
    matDumbbells = "Hanteln",
    matMachine = "Gerät",
    matOther = "weitere Hilfsmittel",
    matAll = "Alle",
)

val EnglishStrings = AppStrings(
    navProfile = "Profile",
    navTrainingPlans = "Training Plans",
    navMyExercises = "My Exercises",
    navAthletes = "Athletes",
    navProgress = "Training Progress",
    navChat = "Chat",
    navTrainingConcept = "Training Concept",
    navOrganization = "Organization",
    navSettings = "Settings",
    navLogout = "Sign Out",
    done = "Done",
    add = "Add",
    cancel = "Cancel",
    delete = "Delete",
    save = "Save",
    edit = "Edit",
    search = "Search",
    close = "Close",
    apply = "Apply",
    confirm = "Confirm",
    back = "Back",
    create = "Create",
    start = "Start",
    next = "Next",
    finish = "Finish",
    myExercises = "My Exercises",
    standardDatabase = "Standard Database",
    searchExercise = "Search exercise…",
    noCustomExercises = "No custom exercises yet.\nAdd your first exercise.",
    loadingExercises = "Loading standard exercises…",
    editImages = "Edit Images",
    newExercise = "New Exercise",
    chooseExercise = "Choose Exercise",
    createNewExercise = "Create New Exercise",
    fromDatabase = "Database",
    trainingPlans = "Training Plans",
    newTrainingPlan = "New Training Plan",
    editPlan = "Edit Plan",
    deletePlan = "Delete Training Plan",
    addExercise = "Add Exercise",
    addFocus = "Add Focus",
    alternativeExercises = "Alternative Exercises",
    addAlternative = "Add",
    rounds = "Rounds",
    sets = "Sets",
    reps = "Reps",
    pause = "Rest",
    seconds = "Seconds",
    settings = "Settings",
    appearance = "Appearance",
    darkMode = "Dark Mode",
    language = "Language",
    weightUnit = "Weight Unit",
    notifications = "Notifications",
    privacy = "Privacy",
    subscription = "Subscription",
    myRole = "My Role",
    roleCoach = "Coach",
    roleAthlete = "Athlete",
    roleBoth = "Both",
    shareProgressWithCoach = "Share progress with coach",
    signOut = "Sign Out",
    todayNoWorkout = "No workout planned today.\nEnjoy your rest day!",
    todayWorkoutTitle = "Today's Workout",
    completedToday = "Completed today",
    notScheduledTitle = "Not scheduled for today",
    notScheduledBody = "Minimum rest period not yet reached. The next workout will be unlocked after the rest period ends.",
    startAnyway = "Start anyway",
    weekdayNames = listOf("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"),
    everyXDays = "Every %d days",
    freelyChoosable = "Freely choosable",
    exerciseCount = "%d exercises",
    roundOf = "Round %d / %d",
    exerciseOf = "Exercise %d / %d",
    alternative = "Alternative",
    chooseExerciseTitle = "Choose Exercise",
    setsLabel = "Sets",
    repsLabel = "Reps",
    workoutCompleted = "Workout completed!",
    shareWorkoutQuestion = "Do you want to share your workout with your coach?",
    shareWorkout = "Share workout",
    dontShare = "Don't share",
    sharePlan = "Share",
    sharePlanTitle = "Share Training Plan",
    individualAthletes = "Individual Athletes",
    workoutNotScheduled = "Workout not scheduled for today",
    workoutNotScheduledBody = "Minimum rest period not yet met. The workout will be unlocked after the rest period ends.",
    endPlan = "End",
    endPlanTitle = "End Training Plan",
    endPlanBody = "The plan will be ended for all athletes and removed from their app.",
    newTrainingPlanCreate = "Create new training plan",
    noPlansCoach = "No training plans yet.\nCreate your first plan.",
    noPlansAthlete = "No training plan shared.\nEnter your coach code.",
    deletePlanBody = "The training plan will be permanently deleted.",
    exercises = "Exercises",
    noExercisesFound = "No exercises found.",
    selectAll = "Select all",
    groupIntoCircuit = "Group exercises into circuit",
    addExercisesFirst = "Add exercises first.",
    circuitExercisesTitle = "Choose Circuit Exercises",
    circuitExercisesBody = "Which exercises should be included in the circuit?",
    navTrainingNotes = "Training Notes",
    noNotesYet = "No notes yet.\nTap + to add your first note.",
    newNote = "New Note",
    writeNote = "Write your note…",
    catAll = "All",
    catBack = "Back",
    catChest = "Chest",
    catShoulders = "Shoulders",
    catCore = "Core",
    catThighs = "Thighs",
    catCalves = "Calves",
    catGlutes = "Glutes",
    catUpperArms = "Upper Arms",
    catCoordination = "Coordination",
    catReflection = "Reflection",
    matBodyweight = "Bodyweight",
    matDumbbells = "Weights",
    matMachine = "Machine",
    matOther = "Other Equipment",
    matAll = "All",
)

val LocalAppStrings = compositionLocalOf<AppStrings> { GermanStrings }

fun appStringsFor(lang: AppLanguage): AppStrings =
    if (lang == AppLanguage.ENGLISH) EnglishStrings else GermanStrings

/** Translates a German category/material string for display (stored key stays German). */
fun AppStrings.translateCategory(german: String): String = when (german) {
    "Rücken" -> catBack
    "Brust" -> catChest
    "Schultern" -> catShoulders
    "Bauch" -> catCore
    "Oberschenkel" -> catThighs
    "Unterschenkel" -> catCalves
    "Becken" -> catGlutes
    "Oberarme" -> catUpperArms
    "Koordination" -> catCoordination
    "Reflektion" -> catReflection
    "Ohne Hilfsmittel" -> matBodyweight
    "Hanteln" -> matDumbbells
    "Gerät" -> matMachine
    "weitere Hilfsmittel" -> matOther
    else -> german
}
